export interface Service {
  id?: number,
  additionalInfo?: string,
  distance?: number,
  endDate: Date,
  price: number,
  species: string[],
  speciesLabels?: string[],
  startDate: Date,
  state: string,
  type: string,
  typeLabel?: string,
  userId: number,
  userName?: string,
}
